# Generated by Django 4.0.5 on 2022-06-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentimentSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=125, null=True)),
                ('sentence', models.TextField()),
                ('sentence_short', models.CharField(blank=True, max_length=125, null=True)),
                ('sentence_keywords', models.CharField(blank=True, max_length=125, null=True)),
                ('sentence_sentiment', models.CharField(blank=True, max_length=125, null=True)),
                ('sentence_sentiment_net', models.FloatField(default=0)),
                ('sentence_sent_score', models.FloatField(default=0)),
                ('sentence_sentiment_label', models.IntegerField(default=1)),
                ('sentence_entities', models.CharField(blank=True, max_length=125, null=True)),
                ('sentence_non_entities', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='young',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('logits', models.FloatField(default=0)),
                ('net_sent', models.FloatField(default=0)),
                ('logits_mean', models.FloatField(default=0)),
                ('net_sent_mean', models.FloatField(default=0)),
                ('MA_logits', models.FloatField(default=0)),
                ('MA_net_sent', models.FloatField(default=0)),
                ('MA_net_sent_ema_alpha_0', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
    ]
