# Generated by Django 4.0.5 on 2022-06-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentsentence',
            name='sentence_entities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentsentence',
            name='sentence_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentsentence',
            name='sentence_non_entities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentsentence',
            name='sentence_sentiment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentsentence',
            name='sentence_short',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
