# Generated by Django 4.0.5 on 2022-06-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_sentimentsentence_sentence_entities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='young',
            old_name='MA_net_sent_ema_alpha_0',
            new_name='MA_net_sent_ema_alpha_1',
        ),
        migrations.AddField(
            model_name='young',
            name='MA_net_sent_ema_alpha_3',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='young',
            name='MA_net_sent_ema_alpha_5',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
